USE [master]
GO

/****** Object:  Database [SIMS]    Script Date: 4/16/2017 2:16:04 PM ******/
CREATE DATABASE [SIMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SIMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SIMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SIMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SIMS_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SIMS] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SIMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SIMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SIMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SIMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SIMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SIMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SIMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SIMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SIMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SIMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SIMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SIMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SIMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SIMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SIMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SIMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SIMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SIMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SIMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SIMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SIMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SIMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SIMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SIMS] SET RECOVERY FULL 
GO

ALTER DATABASE [SIMS] SET  MULTI_USER 
GO

ALTER DATABASE [SIMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SIMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SIMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SIMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SIMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SIMS] SET QUERY_STORE = OFF
GO

USE [SIMS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SIMS] SET  READ_WRITE 
GO

